try:
    print(x)
except:
    print ("sorry somthing went WrOnG")
finally:
    print("a 'try or a except' is found")